export const DATABASE_CONNECTION_TOKEN = `DATABASE_CONNECTION_TOKEN`;
export const BASE_PRODUCT_REPOSITORY_TOKEN = `BASE_PRODUCT_REPOSITORY_TOKEN`;
export const PRODUCT_REPOSITORY_TOKEN = `PRODUCT_REPOSITORY_TOKEN`;
